# Deploy Next.js app to Azure App Service with GitHub Actions

name: Build and deploy Next.js app to Azure Web App - landdingMa

on:
  push:
    branches:
      - main   # se ejecuta cada vez que haces push a main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 1. Clonar repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # mismo runtime que tu App Service

      # 3. Instalar dependencias y generar .next
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # 4. Subir artefacto para usar en deploy
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: |
            .next
            node_modules
            package.json
            package-lock.json
            public
            next.config.js
            tsconfig.json
            # agrega aquí otros archivos que necesite tu app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Descargar artefacto del job de build
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
          path: .

      # 2. Login a Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0AD482FD6BB04E24BF0290D81ADA7095 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B289D5001DE44A118BF9981A78A97E5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2D08558E39FD41389C5C9154B5546FF4 }}

      # 3. Desplegar a App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'landdingMa'
          slot-name: 'Production'
          package: .
