name: Build and deploy Node.js app to Azure Web App - landdingMa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # Empaquetar SOLO lo necesario
      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r .next node_modules package.json package-lock.json public deploy/
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0AD482FD6BB04E24BF0290D81ADA7095 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B289D5001DE44A118BF9981A78A97E5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2D08558E39FD41389C5C9154B5546FF4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'landdingMa'
          slot-name: 'Production'
          package: .
